wip
WIP

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,7 +22,6 @@
 # or visit www.oracle.com if you need additional information or have any
 # questions.
 #
-
 name: 'Run tests'
 
 on:
@@ -70,6 +69,7 @@ jobs:
           - 'hs/tier1 runtime'
           - 'hs/tier1 serviceability'
           - 'lib-test/tier1'
+          - 'docs'
 
         include:
           - test-name: 'jdk/tier1 part 1'
@@ -116,108 +116,78 @@ jobs:
             test-suite: 'test/lib-test/:tier1'
             debug-suffix: -debug
 
+          - platform: linux-x64
+            test-name: 'docs'
+            test-suite: 'test/docs/:tier2'
+
     steps:
       - name: 'Checkout the JDK source'
         uses: actions/checkout@v4
 
-      - name: 'Get MSYS2'
-        uses: ./.github/actions/get-msys2
-        if: runner.os == 'Windows'
-
-      - name: 'Get the BootJDK'
-        id: bootjdk
-        uses: ./.github/actions/get-bootjdk
+      - name: Upload JDK bundle
+        if: steps.upload-bundles.outputs.bundles-found == 'true'
+        uses: actions/upload-artifact@v4
         with:
-          platform: ${{ inputs.bootjdk-platform }}
+          name: jdk-bundle
+          path: bundles/jdk-linux-x64-debug.tar.gz
 
-      - name: 'Get JTReg'
-        id: jtreg
-        uses: ./.github/actions/get-jtreg
-
-      - name: 'Get bundles'
-        id: bundles
-        uses: ./.github/actions/get-bundles
+      - name: Download doc bundle
+        if: matrix.test-name == 'docs'
+        uses: actions/download-artifact@v4
         with:
-          platform: ${{ inputs.platform }}
-          debug-suffix: ${{ matrix.debug-suffix }}
+          name: docs-bundle
+          path: docs_bundle
+
+      - name: Extract doc bundle
+        if: matrix.test-name == 'docs'
+        run: |
+          DOCS_ZIP=$(find docs_bundle -name 'jdk-*-internal_doc-all.zip' | head -n 1)
+          if [ -z "$DOCS_ZIP" ]; then
+            echo "Could not find doc zip bundle"
+            exit 1
+          fi
+
+          # Create expected destination (adjust platform if needed)
+          mkdir -p build/linux-x64/images/docs
+      
+          # Unzip into the expected directory
+          unzip -q "$DOCS_ZIP" -d build/linux-x64/images/docs
+      
+          # Set environment variable for the test
+          echo "DOCS_JDK_IMAGE_DIR=$(pwd)/build/linux-x64/images/docs" >> $GITHUB_ENV
+        
 
       - name: 'Install dependencies'
         run: |
           # On macOS we need to install some dependencies for testing
-          brew install make
-          sudo xcode-select --switch /Applications/Xcode_${{ inputs.xcode-toolset-version }}.app/Contents/Developer
-          # This will make GNU make available as 'make' and not only as 'gmake'
-          echo '/usr/local/opt/make/libexec/gnubin' >> $GITHUB_PATH
-        if: runner.os == 'macOS'
-
-      - name: 'Set PATH'
-        id: path
-        run: |
-          # We need a minimal PATH on Windows
-          # Set PATH to "", so just GITHUB_PATH is included
-          if [[ '${{ runner.os }}' == 'Windows' ]]; then
-            echo "value=" >> $GITHUB_OUTPUT
-          else
-            echo "value=$PATH" >> $GITHUB_OUTPUT
+          if [[ "$OSTYPE" == "darwin"* ]]; then
+            brew install some-dependency
           fi
 
-      - name: 'Run tests'
-        id: run-tests
-        run: >
-          make test-prebuilt
-          TEST='${{ matrix.test-suite }}'
-          BOOT_JDK=${{ steps.bootjdk.outputs.path }}
-          JT_HOME=${{ steps.jtreg.outputs.path }}
-          JDK_IMAGE_DIR=${{ steps.bundles.outputs.jdk-path }}
-          SYMBOLS_IMAGE_DIR=${{ steps.bundles.outputs.symbols-path }}
-          TEST_IMAGE_DIR=${{ steps.bundles.outputs.tests-path }}
-          JTREG='JAVA_OPTIONS=-XX:-CreateCoredumpOnCrash;VERBOSE=fail,error,time;KEYWORDS=!headful'
-          && bash ./.github/scripts/gen-test-summary.sh "$GITHUB_STEP_SUMMARY" "$GITHUB_OUTPUT"
+      - name: Run tests
+        run: |
+          if [[ "${{ matrix.test-name }}" == "docs" ]]; then
+            export DOCS_IMAGE_DIR="$GITHUB_WORKSPACE/build/linux-x64/images/docs"
+            echo "DOCS_IMAGE_DIR=$DOCS_IMAGE_DIR"
+            ls -R "$DOCS_IMAGE_DIR"  # Debugging
+            make test-prebuilt-docs \
+              TEST='${{ inputs.test-suite }}' \
+              BOOT_JDK=$BOOT_JDK \
+              JT_HOME=$JT_HOME \
+              DOCS_IMAGE_DIR=$DOCS_IMAGE_DIR \
+              JTREG='JAVA_OPTIONS=-XX:-CreateCoredumpOnCrash;VERBOSE=fail,error,time;KEYWORDS=!headful'
+          else
+            make test-prebuilt \
+              TEST='${{ matrix.test-suite }}' \
+              BOOT_JDK=${{ steps.bootjdk.outputs.path }} \
+              JT_HOME=${{ steps.jtreg.outputs.path }} \
+              JDK_IMAGE_DIR=${{ steps.bundles.outputs.jdk-path }} \
+              SYMBOLS_IMAGE_DIR=${{ steps.bundles.outputs.symbols-path }} \
+              TEST_IMAGE_DIR=${{ steps.bundles.outputs.tests-path }} \
+              JTREG='JAVA_OPTIONS=-XX:-CreateCoredumpOnCrash;VERBOSE=fail,error,time;KEYWORDS=!headful'
+          fi
+
+          bash ./.github/scripts/gen-test-summary.sh "$GITHUB_STEP_SUMMARY" "$GITHUB_OUTPUT"
+
         env:
           PATH: ${{ steps.path.outputs.value }}
-
-        # This is a separate step, since if the markdown from a step gets bigger than
-        # 1024 kB it is skipped, but then the short summary above is still generated
-      - name: 'Generate test report'
-        run: bash ./.github/scripts/gen-test-results.sh "$GITHUB_STEP_SUMMARY"
-        if: always()
-
-      - name: 'Package test results'
-        id: package
-        run: |
-          # Package test-results and relevant parts of test-support
-          mkdir results
-
-          if [[ -d build/run-test-prebuilt/test-results ]]; then
-            cd build/run-test-prebuilt/test-results/
-            zip -r -9 "$GITHUB_WORKSPACE/results/test-results.zip" .
-            cd $GITHUB_WORKSPACE
-          else
-            echo '::warning ::Missing test-results directory'
-          fi
-
-          if [[ -d build/run-test-prebuilt/test-support ]]; then
-            cd build/run-test-prebuilt/test-support/
-            zip -r -9 "$GITHUB_WORKSPACE/results/test-support.zip" . -i *.jtr -i */hs_err*.log -i */replay*.log
-            cd $GITHUB_WORKSPACE
-          else
-            echo '::warning ::Missing test-support directory'
-          fi
-
-          artifact_name="results-${{ inputs.platform }}-$(echo ${{ matrix.test-name }} | tr '/ ' '__')"
-          echo "artifact-name=$artifact_name" >> $GITHUB_OUTPUT
-        if: always()
-
-      - name: 'Upload test results'
-        uses: actions/upload-artifact@v4
-        with:
-          path: results
-          name: ${{ steps.package.outputs.artifact-name }}
-        if: always()
-
-        # This is the best way I found to abort the job with an error message
-      - name: 'Notify about test failures'
-        uses: actions/github-script@v7
-        with:
-          script: core.setFailed('${{ steps.run-tests.outputs.error-message }}')
-        if: steps.run-tests.outputs.failure == 'true'
